-- finds whether employee numbered 100 worked for more than 10 years in the company.

DECLARE
    HIRING_DATE DATE;
    YEARS_WORKED NUMBER;
BEGIN
    SELECT HIRE_DATE INTO HIRING_DATE
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    YEARS_WORKED := ROUND(MONTHS_BETWEEN(SYSDATE, HIRING_DATE)/12);
    IF YEARS_WORKED > 10 THEN
    DBMS_OUTPUT.PUT_LINE('HE IS WORKING MORE THAN 10 YEARS');
    ELSE 
    DBMS_OUTPUT.PUT_LINE('HE IS WORKING ONLY' || YEARS_WORKED || ' YEARS');
    END IF;
END;
/

-- find the grade level of employee numbered 100.

DECLARE
    EMP_SALARY NUMBER;
BEGIN
    SELECT SALARY INTO EMP_SALARY
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    IF EMP_SALARY < 1000 THEN
    DBMS_OUTPUT.PUT_LINE('GRADE D');
    ELSIF EMP_SALARY >= 1000 AND EMP_SALARY < 2000 THEN
    DBMS_OUTPUT.PUT_LINE('GRADE C');
    ELSIF EMP_SALARY >= 2000 AND EMP_SALARY < 3000 THEN
    DBMS_OUTPUT.PUT_LINE('GRADE B');
    ELSIF EMP_SALARY >= 3000 AND EMP_SALARY < 4000 THEN
    DBMS_OUTPUT.PUT_LINE('GRADE A');
    ELSIF EMP_SALARY >= 4000 THEN
    DBMS_OUTPUT.PUT_LINE('GRADE A+');
    ELSE DBMS_OUTPUT.PUT_LINE('FOKINNI');
    END IF;
END;
/


