-- finds whether employee numbered 100 worked for more than 10 years in the company with exception handling

DECLARE
    HIRING_DATE DATE;
    YEARS_WORKED NUMBER;
BEGIN
    SELECT HIRE_DATE INTO HIRING_DATE
    FROM HR.EMPLOYEES
    WHERE MOD(EMPLOYEE_ID, 2) = 1;  -- TRY WITH EMPLOYEE_ID = 1000;
    YEARS_WORKED := ROUND(MONTHS_BETWEEN(SYSDATE, HIRING_DATE)/12);
    IF YEARS_WORKED > 10 THEN
    DBMS_OUTPUT.PUT_LINE('HE IS WORKING MORE THAN 10 YEARS');
    ELSE 
    DBMS_OUTPUT.PUT_LINE('HE IS WORKING ONLY' || YEARS_WORKED || ' YEARS');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO DATA HAS BEEN FOUND.');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');
END;
/

-- WITH TOO MANY ROWS HANDLING FOR MORE READABILITY'

DECLARE
    HIRING_DATE DATE;
    YEARS_WORKED NUMBER;
BEGIN
    SELECT HIRE_DATE INTO HIRING_DATE
    FROM HR.EMPLOYEES
    WHERE MOD(EMPLOYEE_ID, 2) = 1;
    YEARS_WORKED := ROUND(MONTHS_BETWEEN(SYSDATE, HIRING_DATE)/12);
    IF YEARS_WORKED > 10 THEN
    DBMS_OUTPUT.PUT_LINE('HE IS WORKING MORE THAN 10 YEARS');
    ELSE 
    DBMS_OUTPUT.PUT_LINE('HE IS WORKING ONLY' || YEARS_WORKED || ' YEARS');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO DATA HAS BEEN FOUND.');
    WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE('TOO MANY DATA FILLS THIS CRITERIA.');
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('SOMETHING WENT WRONG');
END;
/