-- find whether employee has worked 10 years or more with function.

CREATE OR REPLACE FUNCTION GET_SENIOR_EMPLOYEE(E_ID IN NUMBER)
RETURN VARCHAR2 IS 
    HIRING_DATE DATE;
    YEARS NUMBER;
    MSG VARCHAR2(100);
BEGIN 
    SELECT HIRE_DATE INTO HIRING_DATE 
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = E_ID;

    YEARS := ROUND(MONTHS_BETWEEN(SYSDATE, HIRING_DATE)/12);

    IF YEARS >= 10 THEN 
        MSG := 'HE IS A SENIOR EMPLOYEE.';
    ELSE 
        MSG := 'HE IS NOT A SENIOR EMPLOYEE.';
    END IF;
    RETURN MSG;
EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        RETURN 'NO DATA FOUND WITH THAT EMPLOYEE ID.';
    WHEN OTHERS THEN 
        RETURN 'SOMETHING WENT WRONG.';
END;
/

-- FUNCTION CALL : 

-- OPTION 1:
SELECT GET_SENIOR_EMPLOYEE(100)    -- THIS IS THE REASON WHY FUNCTION EXISTS IN SQL AS PROCEDURE CAN ALSO RETURN VALUES
FROM HR.EMPLOYEES;

-- OPTION 2:
DECLARE 
    MSG VARCHAR2(100);
BEGIN 
    MSG := GET_SENIOR_EMPLOYEE(102);
    DBMS_OUTPUT.PUT_LINE(MSG);
    MSG := GET_SENIOR_EMPLOYEE(105);
    DBMS_OUTPUT.PUT_LINE(MSG);
    MSG := GET_SENIOR_EMPLOYEE(10000);
    DBMS_OUTPUT.PUT_LINE(MSG);
END;
/

