-- find whether employee has worked 10 years or more with nested block.
CREATE OR REPLACE FUNCTION GET_SENIOR_EMPLOYEE(EMP_ID IN NUMBER)
RETURN VARCHAR2 IS 
    MSG VARCHAR2(100);
    EMP_COUNT NUMBER;
    HIRING_DATE DATE;
    YEARS NUMBER;
BEGIN 
    BEGIN 
        SELECT COUNT(*) INTO EMP_COUNT 
        FROM HR.EMPLOYEES
        WHERE EMPLOYEE_ID = EMP_ID;
    END;

    IF EMP_COUNT = 0 THEN 
        MSG := 'NO EMPLOYEE FOUND.';
    ELSE 
        SELECT HIRE_DATE INTO HIRING_DATE
        FROM HR.EMPLOYEES
        WHERE EMPLOYEE_ID = EMP_ID;

        YEARS := ROUND(MONTHS_BETWEEN(SYSDATE, HIRING_DATE)/12);

        IF YEARS >= 10 THEN 
            MSG := 'HE IS A SENIOR EMPLOYEE.';
        ELSE 
            MSG := 'HE IS A JUNIOR EMPLOYEE.';
        END IF;
    END IF;
    RETURN MSG;
END;
/

-- FUNCTION CALL :
DECLARE 
    MSG VARCHAR2(100);
BEGIN 
    MSG := GET_SENIOR_EMPLOYEE(102);
    DBMS_OUTPUT.PUT_LINE(MSG);
    MSG := GET_SENIOR_EMPLOYEE(105);
    DBMS_OUTPUT.PUT_LINE(MSG);
    MSG := GET_SENIOR_EMPLOYEE(10000);
    DBMS_OUTPUT.PUT_LINE(MSG);
END;
/

-- HERE NO EXCEPTION NEEDED BECAUSE ALREADY WE ARE DETERMINING FIRST, IS THERE ANY EMPLOYEE EXISTS OR NOT WITH THAT EMPLOYEE_ID.
-- BUT EXCEPTION CAN BE THERE IF NEEDED.
