-- THESE ARE THE PROBLEM EXAMPLES OF SUKARNA SIR'S BOOK'S PL/SQL PART

-- 1.
CREATE TABLE LOG_TABLE_CGPA_UPDATE(
    USERNAME VARCHAR2(50),
    UPDATE_TIME DATE
);

CREATE OR REPLACE TRIGGER LOG_CGPA_UPDATE
AFTER UPDATE 
OF CGPA
ON STUDENTS
DECLARE 
    USERNAME VARCHAR2(50);
BEGIN 
    USERNAME := USER;
    INSERT INTO LOG_TABLE_CGPA_UPDATE VALUES(USERNAME, SYSDATE);
END;
/

-- UPDATES
UPDATE STUDENTS SET CGPA = CGPA - 0.01
WHERE STUDENT_NAME LIKE '%LE';

UPDATE STUDENTS SET CGPA = CGPA + 0.01 ;

-- FOR TESTING
SELECT * FROM LOG_TABLE_CGPA_UPDATE;
SELECT * FROM STUDENTS;

-- 2. 
CREATE TABLE STUDENTS_DELETED (
    STUDENT_NAME VARCHAR2(250),
    CGPA NUMBER,
    DELETED_BY VARCHAR2(50),
    UPDATE_TIME TIMESTAMP
);

CREATE OR REPLACE TRIGGER BACKUP_DELETED_STUDENTS
BEFORE DELETE 
ON STUDENTS
FOR EACH ROW
DECLARE 
    
BEGIN
    INSERT INTO STUDENTS_DELETED VALUES(:OLD.STUDENT_NAME, :OLD.CGPA, USER, CURRENT_TIMESTAMP);
END;
/

-- UPDATES
DELETE FROM STUDENTS WHERE CGPA < 3.50 ;

-- TESTING
SELECT * FROM STUDENTS_DELETED;
SELECT * FROM STUDENTS;

-- 3.
CREATE OR REPLACE TRIGGER CORRECT_STUDENT_NAME
BEFORE INSERT
ON STUDENTS
FOR EACH ROW 
DECLARE
BEGIN
    :NEW.STUDENT_NAME := INITCAP(:NEW.STUDENT_NAME) ;
END ;
/

-- CHANGES
INSERT INTO STUDENTS VALUES ('MaRIa joHNson', 3.78);
INSERT INTO STUDENTS VALUES ('MItchel StaRC', 3.80);

-- TESTING
SELECT * FROM STUDENTS;