-- find whether employee numbered 100 has worked 10 years or more. Let us call this procedure IS_SENIOR_EMPLOYEE.
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE IS_HE_SENIOR_EMPLOYEE IS 
    J_DATE DATE;
    YEARS  NUMBER;
BEGIN
    SELECT HIRE_DATE INTO J_DATE
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 100;
    
    YEARS := ROUND(MONTHS_BETWEEN(SYSDATE, J_DATE)/12);
    IF YEARS >= 10 THEN 
        DBMS_OUTPUT.PUT_LINE('THE WORKER WITH ID NO 100 WORKED 10 YEARS OR MORE.');
    ELSE DBMS_OUTPUT.PUT_LINE('THE WORKER WITH ID NO 100 DID NOT WORK 10 YEARS OR MORE.');
    END IF;
END;
/

DECLARE 

BEGIN 
    IS_HE_SENIOR_EMPLOYEE;
END;
/


-- USE OF PROCEDURE PARAMETERS & EXCEPTION HANDLING

--user will select which id should be choosen
CREATE OR REPLACE PROCEDURE IS_HE_SENIOR_EMPLOYEE(EMP_ID IN VARCHAR2, MSG OUT VARCHAR2) IS 
    J_DATE DATE;
    YEARS  NUMBER;
BEGIN
    SELECT HIRE_DATE INTO J_DATE
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = EMP_ID;
    
    YEARS := ROUND(MONTHS_BETWEEN(SYSDATE, J_DATE)/12);
    IF YEARS >= 10 THEN 
        MSG := 'THE WORKER WITH ID NO 100 WORKED 10 YEARS OR MORE.';
    ELSE MSG := 'THE WORKER WITH ID NO 100 DID NOT WORK 10 YEARS OR MORE.';
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        MSG := 'NO DATA FOUND.';
    WHEN TOO_MANY_ROWS THEN 
        MSG := 'TOO MANY DATA FOUND.';
    WHEN OTHERS THEN 
        MSG := 'SOMETHING WENT WRONG.';
END;
/

DECLARE 
    MSG VARCHAR2;
BEGIN 
    -- IS_HE_SENIOR_EMPLOYEE(100);
    -- IS_HE_SENIOR_EMPLOYEE(101);
    -- IS_HE_SENIOR_EMPLOYEE(10000);
    IS_HE_SENIOR_EMPLOYEE(104, MSG);
    DBMS_OUTPUT.PUT_LINE(MSG);
    IS_HE_SENIOR_EMPLOYEE(10694, MSG);
    DBMS_OUTPUT.PUT_LINE(MSG);
END;
/