-- CREATING TABLE : 
CREATE TABLE STUDENTS(
STUDENT_NAME VARCHAR2(250),
CGPA NUMBER
) ;

SELECT DISTINCT * 
FROM STUDENTS;

-- THIS TRIGGER ENSURES THAT AFTER EVERY INSERTION INTO STUDENTS TABLE IT WILL PRINT 'HELLO WORLD !'.
CREATE OR REPLACE TRIGGER HW
AFTER INSERT 
ON STUDENTS

DECLARE 

BEGIN 
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD !');
END;
/

INSERT INTO STUDENTS VALUES ('Fahim Hasan', 3.71);
INSERT INTO STUDENTS VALUES ('Ahmed Nahiyan', 3.80);
INSERT INTO STUDENTS VALUES ('JOHNNY BAIRSTOW', 3.63);
INSERT INTO STUDENTS VALUES ('VIRAT KOHLI', 4.00);


-- VARIATIONS OF THIS TRIGGER

-- 1. BEFORE INSERT PRINT 'HELLO WORLD !'
CREATE OR REPLACE TRIGGER HW1
BEFORE INSERT
ON STUDENTS

DECLARE 

BEGIN 
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD BEFORE INSERTION !');
END;
/

INSERT INTO STUDENTS VALUES('ROHIT SHARMA', 3.45);
INSERT INTO STUDENTS VALUES('DAVID WARNER', 3.31);

-- 2. AFTER INSERT OR DELETE PRINT 'HELLO WORLD !'
CREATE OR REPLACE TRIGGER HW2
AFTER INSERT OR DELETE
ON STUDENTS

DECLARE 

BEGIN 
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD AFTER INSERTION OR DELETION !');
END;
/

INSERT INTO STUDENTS VALUES('JOE ROOT', 3.66);
INSERT INTO STUDENTS VALUES('SHAKIB AL HASAN', 3.75);


-- 3. run when update is performed on the CGPA column.
CREATE OR REPLACE TRIGGER HW3
AFTER UPDATE 
OF CGPA 
ON STUDENTS 
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD AFTER UPDATING ON CGPA COLUMN!');
END ;
/

UPDATE STUDENTS SET CGPA = CGPA + 0.2
WHERE CGPA < 3.50;
UPDATE STUDENTS SET STUDENT_NAME = 'BADHON PAIN'  -- TRIGGER WON'T GET CALLED FOR THAT STATEMENT
WHERE STUDENT_NAME  LIKE 'Ahmed Nahiyan';


-- 4. this trigger will run N times if N rows are affected by the SQL statement.
CREATE OR REPLACE TRIGGER HW4
AFTER UPDATE 
OF CGPA 
ON STUDENTS 
FOR EACH ROW
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE('THIS ROW IS UPDATED !');
END ;
/

UPDATE STUDENTS SET CGPA = CGPA + 0.2
WHERE CGPA < 3.50;
UPDATE STUDENTS SET STUDENT_NAME = 'SHAHRUKH KHAN'  -- TRIGGER WON'T GET CALLED FOR THAT STATEMENT
WHERE STUDENT_NAME  LIKE 'Fahim Hasan';

SELECT * FROM STUDENTS;   -- FOR TESTING

INSERT INTO STUDENTS VALUES ('JOS BUTTLER', 3.63);
DELETE FROM STUDENTS WHERE CGPA < 3.65 ;
UPDATE STUDENTS SET CGPA = CGPA + 0.01 
WHERE STUDENT_NAME LIKE '%an';

-- OLD AND NEW REFERENCE

CREATE OR REPLACE TRIGGER OLD_NEW_TEST
BEFORE INSERT OR UPDATE OR DELETE
ON STUDENTS
FOR EACH ROW
DECLARE
BEGIN
    DBMS_OUTPUT.PUT_LINE(':OLD.CGPA = ' || :OLD.CGPA) ;
    DBMS_OUTPUT.PUT_LINE(':NEW.CGPA = ' || :NEW.CGPA) ;
END ;
/

-- CHANGES
INSERT INTO STUDENTS VALUES ('SOUMIK SARKAR', 3.85);
UPDATE STUDENTS SET CGPA = CGPA + 0.02 ;
DELETE FROM STUDENTS WHERE CGPA < 3.75;

-- FOR TESTING
SELECT * FROM STUDENTS;

-- DELETE OR REMOVE A TRIGGER
DROP TRIGGER OLD_NEW_TEST ;