-- LEFT ANTI JOIN : ONLY FROM LEFT WHO DOESN'T MATCH WITH RIGHT
-- GET ALL CUSTOMERS WHO HAVEN'T PLACED ANY ORDER 

SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NULL;

-- RIGHT ANTI JOIN : ONLY FROM RIGHT WHO DOESN'T MATCH WITH LEFT
-- GET ALL ORDERS WITHOUT MATCHING CUSTOMERS
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
RIGHT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID
WHERE C.ID IS NULL;

-- SAME TASK WITH LEFT JOIN
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES 
FROM ORDERS AS O
LEFT JOIN CUSTOMERS AS C
ON C.ID = O.CUSTOMER_ID
WHERE C.ID IS NULL;

-- FULL ANTI JOIN : NO MATCHES IN EITHER TABLES
-- FIND CUSTOMERS WITHOUT ORDERS AND ORDERS WITHOUT CUSTOMERS 
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NULL
UNION
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
RIGHT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID
WHERE C.ID IS NULL;
 
-- CHALLENGE TASK : FIND ALL THE CUSTOMER WHO HAVE PLACED ORDERS WITHOUT USING INNER JOIN

SELECT *
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID
WHERE O.CUSTOMER_ID IS NOT NULL;

-- CROSS JOIN : EVERYTHING FROM LEFT TABLE TO EVERYTHING WITH RIGHT TABLE
SELECT *
FROM CUSTOMERS
CROSS JOIN ORDERS;  
