-- NO JOIN 
-- TASK : JUST SIMPLY OUTPUT ORDERS AND CUSTOMERS TABLES SIDE IN TWO QUERY 
SELECT *
FROM orders;

SELECT *
FROM customers;

-- INNER JOIN :  ONLY MATCHING
-- GET ALL CUSTOMERS ALONG WITH THEIR ORDERS BUT ONLY WHO HAVE PLACED ORDERS

SELECT  
	C.ID,
	C.FIRST_NAME, 
    O.ORDER_ID,
    O.SALES
FROM CUSTOMERS AS C
INNER JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID;

-- LEFT JOIN : LEFT ALL + MATCHINGS
-- GET ALL CUSTOMERS ALONG WITH ORDERS INCLUDING THOSE WITHOUT ORDERS

SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID;   

-- SAME TASK USING RIGHT JOIN 
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM ORDERS AS O
RIGHT JOIN CUSTOMERS AS C
ON O.CUSTOMER_ID = C.ID;


-- RIGHT JOIN : MATCHING + RIGHT ALL
-- GET CUSTOMERS ALONG WITH ORDERS INCLUDING ORDERS WITHOUT MATCHING CUSTOMERS

SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
RIGHT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID; 

-- SAME TASK WITH LEFT JOIN : JUST CHANGE THE TABLE ORDER 
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM ORDERS AS O
LEFT JOIN CUSTOMERS AS C
ON C.ID = O.CUSTOMER_ID;

-- FULL JOIN : MYSQL DOESN'T HAVE THE KEYWORD FULL JOIN BUT CAN BE ACHIEVED...
-- LEFT ALL + RIGHT ALL 
-- GET ALL THE CUSTOMERS AND ORDERS EVEN IF THERE IS NO MATCH

SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
LEFT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID
UNION
SELECT 
		C.ID,
		C.FIRST_NAME,
        O.ORDER_ID,
        O.SALES
FROM CUSTOMERS AS C
RIGHT JOIN ORDERS AS O
ON C.ID = O.CUSTOMER_ID;
 

 