-- TASK: USING SALESDB, RETRIVE A LIST OF ALL ORDERS, ALONG WITH THE RELATED CUSTOMER, PRODUCT AND EMPLOYEE DETAILS
USE SALESDB;
SELECT 
	O.ORDERID,
    O.SALES,
    C.FIRSTNAME AS "CUSTOMER_NAME",
    P.PRODUCT,
    P.PRICE,
    E.FIRSTNAME AS "EMPLOYEE_NAME"
FROM ORDERS AS O
LEFT JOIN CUSTOMERS AS C
ON O.CUSTOMERID = C.CUSTOMERID
LEFT JOIN PRODUCTS AS P
ON O.PRODUCTID = P.PRODUCTID
LEFT JOIN EMPLOYEES AS E
ON O.SALESPERSONID = E.EMPLOYEEID;

-- TASK : Retrieve a list of all orders along with the customer’s full name, the product name and category, 
-- the salesperson’s full name, the salesperson’s department, and the salesperson’s manager’s full name. 
-- Also show the order status and total sales. 

SELECT 
	O.ORDERID,
    CONCAT(C.FIRSTNAME, " ", COALESCE(C.LASTNAME, "")) AS CUSTOMER_NAME,
    P.PRODUCT,
    P.CATEGORY,
    CONCAT(E.FIRSTNAME, " ", COALESCE(E.LASTNAME, "")) AS EMPLOYEE_NAME,
    E.DEPARTMENT,
    CONCAT(E_2.FIRSTNAME, " ", COALESCE(E_2.LASTNAME, "")) AS MANAGER_NAME,
    O.ORDERSTATUS,
    O.SALES
FROM ORDERS AS O
LEFT JOIN CUSTOMERS AS C
ON O.CUSTOMERID = C.CUSTOMERID
LEFT JOIN PRODUCTS AS P
ON O.PRODUCTID = P.PRODUCTID
LEFT JOIN EMPLOYEES AS E
ON O.SALESPERSONID = E.EMPLOYEEID
LEFT JOIN EMPLOYEES AS E_2
ON E.MANAGERID = E_2.EMPLOYEEID;

-- TASK : Retrieve a list of all employees who have made at least one order, along with their full name, department, 
-- manager's full name, and the total number of orders and total sales they generated.

SELECT 
	E.EMPLOYEEID,
    CONCAT(E.FIRSTNAME, " ", COALESCE(E.LASTNAME, "")) AS EMPLOYEE_NAME,
    E.DEPARTMENT,
    CONCAT(E_2.FIRSTNAME, " ", COALESCE(E_2.LASTNAME, "")) AS MANAGER_NAME,
    COUNT(O.ORDERID) AS TOTAL_ORDERS,
	SUM(O.SALES) AS TOTAL_SALES
FROM EMPLOYEES AS E
INNER JOIN ORDERS AS O
ON E.EMPLOYEEID = O.SALESPERSONID
LEFT JOIN EMPLOYEES AS E_2
ON E.MANAGERID = E_2.EMPLOYEEID
GROUP BY E.EMPLOYEEID;


