-- CHAPTER 4 : AGGREGATE FUNCTIONS

-- 1. Retrieve Aggregate Information: Simple GROUP BY queries
SELECT DEPARTMENT_ID, SUM(SALARY)  
FROM HR.EMPLOYEES 
GROUP BY DEPARTMENT_ID ;

SELECT JOB_ID, MAX(SALARY), MIN(SALARY), AVG(SALARY)  
FROM HR.EMPLOYEES 
GROUP BY JOB_ID; 

SELECT DEPARTMENT_ID, COUNT(*) 
FROM HR.EMPLOYEES 
GROUP BY DEPARTMENT_ID ; 

--  Omitting GROUP BY clause in group function query 
-- Will calculate for the whole table
SELECT COUNT(*)
FROM HR.EMPLOYEES;

SELECT MAX(SALARY), MIN(SALARY), AVG(SALARY)
FROM HR.EMPLOYEES;

SELECT JOB_ID , MAX(SALARY), MIN(SALARY), ROUND(AVG(SALARY), 2) "AVG SALARY"
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 80
GROUP BY JOB_ID;

SELECT JOB_ID , MAX(SALARY), MIN(SALARY), ROUND(AVG(SALARY), 2) "AVG SALARY"
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 80
GROUP BY JOB_ID
ORDER BY JOB_ID DESC;

SELECT DEPARTMENT_ID,
       JOB_ID,
       SUM(SALARY)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID;

-- Practice 4.1

-- a.
SELECT MANAGER_ID, COUNT(*)
FROM HR.EMPLOYEES
GROUP BY MANAGER_ID;

-- b.
SELECT DEPARTMENT_ID, COUNT(*)
FROM HR.EMPLOYEES
WHERE SALARY > 10000  -- ORIGINAL: 30000
GROUP BY DEPARTMENT_ID;

-- c.
SELECT DEPARTMENT_ID , MAX(SALARY) "MAX_SALARY", MIN(SALARY) "MIN_SALARY", ROUND(AVG(SALARY),2) "AVG_SALARY)"
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID <> 80
GROUP BY DEPARTMENT_ID
ORDER BY AVG(SALARY) DESC, MAX(SALARY) DESC, MIN(SALARY) DESC;

-- 2. DISTINCT and HAVING in GROUP BY queries

SELECT JOB_ID, MAX(DISTINCT SALARY), MIN(DISTINCT SALARY),  
                SUM(DISTINCT SALARY), COUNT(DISTINCT DEPARTMENT_ID) 
FROM HR.EMPLOYEES  
WHERE DEPARTMENT_ID = 80 
GROUP BY JOB_ID  
ORDER BY JOB_ID ASC ; 


SELECT DEPARTMENT_ID, MAX(SALARY), MIN(SALARY)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING DEPARTMENT_ID <> 80;

SELECT JOB_ID, AVG(SALARY)  
FROM HR.EMPLOYEES  
GROUP BY JOB_ID 
HAVING AVG(SALARY) <= 5000  
ORDER BY AVG(SALARY) DESC ; 

-- Practice 4.2

-- a.
SELECT DEPARTMENT_ID, ROUND(AVG(SALARY), 2)
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING AVG(SALARY) <= 50000;

-- 3. Advanced GROUP BY queries

SELECT TO_CHAR(HIRE_DATE, 'YYYY') YEAR, COUNT(*) TOTAL
FROM HR.EMPLOYEES  
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY') 
ORDER BY YEAR ASC ;

SELECT SUBSTR(FIRST_NAME, 1, 1) FC, COUNT(*) TOTAL 
FROM HR.EMPLOYEES  
GROUP BY SUBSTR(FIRST_NAME, 1, 1)  
ORDER BY FC ASC ;

SELECT JOB_ID, JOB_TITLE, COUNT(*) TOTAL 
FROM HR.JOBS 
GROUP BY JOB_ID, JOB_TITLE ; 

-- Practice 4.3

-- a.
SELECT FLOOR(SALARY/5000)*5 || 'K - <' ||
       (FLOOR(SALARY/5000)+1)*5 || 'K' AS Salary_Group,
       COUNT(*) AS NUMBER_OF_EMPLOYEES
FROM HR.EMPLOYEES
GROUP BY FLOOR(SALARY/5000)
ORDER BY FLOOR(SALARY/5000);

-- b.
SELECT TO_CHAR(HIRE_DATE, 'YYYY'), JOB_ID, COUNT(*) EMPLOYEES
FROM HR.EMPLOYEES
GROUP BY TO_CHAR(HIRE_DATE, 'YYYY'), JOB_ID;