-- CHAPTER 3 : Use of Oracle Single Row Functions

-- 1. CHARACTER FUNCTIONS

-- CASE COVERSION FUNCTIONS
SELECT (INITCAP(FIRST_NAME) || ' ' || LOWER(LAST_NAME)) NAME, UPPER(JOB_ID) JOB
FROM HR.EMPLOYEES;

SELECT *
FROM HR.DEPARTMENTS
WHERE  UPPER(DEPARTMENT_NAME) LIKE '%SALE%';
-- OR,
SELECT *
FROM HR.DEPARTMENTS
WHERE  LOWER(DEPARTMENT_NAME) LIKE '%sale%';

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) NAME, JOB_ID
FROM HR.EMPLOYEES
WHERE INSTR(JOB_ID,'CLERK') > 0;

SELECT (SUBSTR(FIRST_NAME, 1, 1) || SUBSTR(LAST_NAME, 1, 1) || '.') ABBR, SALARY
FROM HR.EMPLOYEES;

SELECT INITCAP(CONCAT(TRIM(FIRST_NAME),' ',TRIM(LAST_NAME))) NAME, LPAD(SALARY, 6 ,0) ROUNDED_SALARY
FROM HR.EMPLOYEES;

-- Practice 3.1

-- a.
SELECT UPPER(CONCAT(SUBSTR(COUNTRY_NAME, 1, 3), SUBSTR(COUNTRY_NAME, -3))) ABBR
FROM HR.COUNTRIES;

-- b.
SELECT LPAD(CONCAT(FIRST_NAME,' ' ,LAST_NAME), 60, '*') "FULL NAME"
FROM HR.EMPLOYEES;

-- c.
SELECT JOB_TITLE
FROM HR.JOBS
WHERE INSTR(LOWER(JOB_TITLE),'manager') > 0;

-- 2. NUMBER FUNCTIONS

SELECT FIRST_NAME, ROUND(SALARY/1000, 2) "SALARY (IN THOUSAND)"
FROM HR.EMPLOYEES
WHERE INSTR(JOB_ID, 'CLERK') > 0;

SELECT FIRST_NAME, ROUND((SYSDATE - HIRE_DATE)/7, 4) "WEEKS EMPLOYED"
FROM HR.EMPLOYEES
WHERE INSTR(JOB_ID, 'CLERK') > 0;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) NAME, 
            (TRUNC(SALARY/1000, 0) || ' THOUSANDS ' || 
            TRUNC(MOD(SALARY, 1000)/100, 0) || ' HUNDREDS ' || 
            MOD(SALARY, 100) || ' TAKA ONLY ') "SALARY (IN WRITING)", SALARY
FROM HR.EMPLOYEES;

-- Practice 3.2

-- a.
SELECT LAST_NAME, ROUND((SYSDATE - HIRE_DATE), 2) "DAYS WORKED"
FROM HR.EMPLOYEES;

-- b.
SELECT LAST_NAME , TRUNC(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 3) "YEARS WORKED"
FROM HR.EMPLOYEES;

-- 3. DATE FUNCTIONS

-- Use of SYSDATE
SELECT LAST_NAME, (SYSDATE - HIRE_DATE)/7 "WEEKS EMPLOYED" 
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID = 80 ;

-- Date Arithmatic

-- VALID OPERATIONS:
-- DATE - DATE
-- DATE + NUMBER
-- DATE - NUMBER

-- DATE Manipulation FUNCTIONS:

SELECT LAST_NAME, MONTHS_BETWEEN(SYSDATE, HIRE_DATE) MON_EMPLOYED 
FROM HR.EMPLOYEES ; 

-- Practice 3.3

-- a.
SELECT FIRST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12, 2) "YEARS WORKED"
FROM HR.EMPLOYEES;

-- b.
SELECT LAST_NAME,
       HIRE_DATE,
       ADD_MONTHS(HIRE_DATE, 1) AS END_OF_FIRST_MONTH,
       ADD_MONTHS(HIRE_DATE, 1) - HIRE_DATE AS DAYS_IN_FIRST_MONTH
FROM HR.EMPLOYEES;

-- 4. Functions for manipulating NULL values

-- NVL FUNCTION

SELECT LAST_NAME, NVL(COMMISSION_PCT, 0) "COMMISSION_PCT"
FROM HR.EMPLOYEES;

-- Check whose COMMISSION_PCT IS NULL
SELECT LAST_NAME, COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE NVL(COMMISSION_PCT, -1) = -1;

SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) "NAME", (SALARY + SALARY*NVL(COMMISSION_PCT, 0)) "SALARY"
FROM HR.EMPLOYEES;

-- Practice 3.4

-- a.
SELECT FIRST_NAME, COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE NVL(COMMISSION_PCT, 0) >= 0.2;

-- b.
SELECT LAST_NAME,
       NVL(SALARY, 0) * 66 AS "SALARY OF 5Y 6M"
FROM HR.EMPLOYEES;

-- 5. Data Type Conversion Functions 

-- Explicit type conversion: TO_CHAR function 
SELECT LAST_NAME, TO_CHAR(HIRE_DATE, 'DD MON, YYYY') "JOINING DATE"
FROM HR.EMPLOYEES;

SELECT LAST_NAME, TO_CHAR(HIRE_DATE, 'Ddspth MONTH, YYYY') "JOINING DATE"
FROM HR.EMPLOYEES;

-- Explicit type conversion: TO_NUMBER function 
SELECT STREET_ADDRESS, POSTAL_CODE 
FROM HR.LOCATIONS 
ORDER BY POSTAL_CODE ASC ; 
-- WON'T GIVE THE EXPECTED OUTPUT, CORRECT :
SELECT STREET_ADDRESS, POSTAL_CODE
FROM HR.LOCATIONS
WHERE REGEXP_LIKE(POSTAL_CODE, '^[0-9]+$')
ORDER BY TO_NUMBER(POSTAL_CODE);

-- Explicit type conversion: TO_DATE function 
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) "NAME", TO_CHAR(HIRE_DATE, 'DD-MON-YYYY') "HIRE DATE"
FROM HR.EMPLOYEES
WHERE HIRE_DATE < TO_DATE('01-JAN-2017', 'DD-MON-YYYY')
ORDER BY HIRE_DATE ASC;

-- Practice 3.5

-- a.
-- i.
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) "NAME", TO_CHAR(HIRE_DATE, 'DDth Month, YYYY') "HIRE DATE"
FROM HR.EMPLOYEES;

-- ii.
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) "NAME", TO_CHAR(HIRE_DATE, 'DD Month, YYYY') "HIRE DATE"
FROM HR.EMPLOYEES;