-- CHAPTER 2 : RETRIEVE DATA FROM DB TABLES
-- 1. Selecting Data using basic SELECT statement

-- Alias of a column
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY*12 ANNUAL_SALARY
FROM HR.EMPLOYEES;

-- Space containing alias
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY*12 "ANNUAL SALARY"
FROM HR.EMPLOYEES;

-- Checking null values
SELECT FIRST_NAME, COMMISSION_PCT
FROM HR.EMPLOYEES;

-- Any arithmatic operation on null values simply returns null
SELECT FIRST_NAME, (SALARY + SALARY*COMMISSION_PCT) "FINAL SALARY"
FROM HR.EMPLOYEES;

-- Concatenation operation ||
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME", SALARY
FROM HR.EMPLOYEES;

-- Use of DISTINCT keyword
SELECT DISTINCT JOB_ID
FROM HR.EMPLOYEES;

-- Use of DISTINCT to remove duplicate tuples
SELECT DISTINCT DEPARTMENT_ID, JOB_ID
FROM HR.EMPLOYEES;

-- Use of DESCRIBE statement
DESCRIBE HR.EMPLOYEES;

-- Practice 2.1
-- a.
SELECT COUNTRY_NAME
FROM HR.COUNTRIES;

-- b.
SELECT JOB_TITLE
FROM HR.JOBS;

-- c.
SELECT MANAGER_ID
FROM HR.EMPLOYEES;


-- d.
SELECT DISTINCT CITY
FROM HR.LOCATIONS;

-- e.
SELECT LOCATION_ID, (STREET_ADDRESS || ', ' || CITY || ', ' || STATE_PROVINCE || ', ' || POSTAL_CODE) ADDRESS 
FROM HR.LOCATIONS;

-- 2.SELECT statement with WHERE clause

SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME", (SALARY+SALARY*COMMISSION_PCT) "FULL SALARY"
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL;

SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE HIRE_DATE > '02-MAR-2016';

-- Use of BETWEEN _ AND _ operator
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-2015' AND '01-JAN-2016' ;

-- Use of IN operator
SELECT FIRST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE LAST_NAME IN ('Chung', 'Pain', 'Bates', 'Austin');

SELECT FIRST_NAME, SALARY 
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (10,20,30,40,50);

-- Joining multiple conditions
SELECT LAST_NAME, SALARY 
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID <> 80 AND  
        (SALARY > 5000 OR COMMISSION_PCT IS NOT NULL) ;

SELECT LAST_NAME, SALARY 
FROM HR.EMPLOYEES 
WHERE (DEPARTMENT_ID = 80 AND SALARY > 5000) OR 
         COMMISSION_PCT IS NOT NULL  ; 
    
-- Pattern matching using LIKE operator

SELECT LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE '%a_s';

-- Coparing with NULL values

SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT = NULL;
-- won't give the result as expected
-- correct way :
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

-- Practice 2.2

-- a.
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE HIRE_DATE < '01-JAN-2018';

-- b.
SELECT *
FROM HR.COUNTRIES
WHERE COUNTRY_NAME IN ('Canada', 'Germany', 'United Kingdom');

-- c.
SELECT FIRST_NAME
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT IS NULL;

-- d.
SELECT FIRST_NAME
FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE '%s';

-- e.
SELECT FIRST_NAME
FROM HR.EMPLOYEES
WHERE LAST_NAME LIKE 's%n';

-- f.
SELECT DEPARTMENT_NAME
FROM HR.DEPARTMENTS
WHERE MANAGER_ID = 100;

-- g. ---
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE JOB_ID = 'AD_PRES' AND SALARY >= 23000;


-- h.
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME"
FROM HR.EMPLOYEES
WHERE LAST_NAME NOT LIKE '%s%';

-- i.
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME", COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE COMMISSION_PCT <= 0.3;

-- j.
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME", HIRE_DATE
FROM HR.EMPLOYEES
WHERE HIRE_DATE > '01-JAN-2015';

-- k.
SELECT (FIRST_NAME || ' ' || LAST_NAME) "FULL NAME", HIRE_DATE
FROM HR.EMPLOYEES
WHERE HIRE_DATE BETWEEN '01-JAN-2015' AND '31-DEC-2015';


-- 3. Sorting Rows in the Output

-- ORDER BY Clause
SELECT LAST_NAME , SALARY
FROM HR.EMPLOYEES
ORDER BY SALARY DESC ; -- by default ASC

SELECT LAST_NAME, SALARY, HIRE_DATE
FROM HR.EMPLOYEES
ORDER BY HIRE_DATE ASC;

-- Sorting based on mutiple columns
SELECT LAST_NAME, SALARY 
FROM HR.EMPLOYEES 
ORDER BY SALARY DESC, LAST_NAME ASC ; 

-- Column aliasing in Ordering
SELECT JOB_TITLE, (MAX_SALARY - MIN_SALARY) DIFF_SALARY
FROM HR.JOBS
ORDER BY DIFF_SALARY DESC;

-- Practice 2.3

-- a.
SELECT FIRST_NAME, SALARY, COMMISSION_PCT
FROM HR.EMPLOYEES
WHERE JOB_ID = 'SA_REP'  -- ORIGINAL : JOB_ID = 'AD_PRES'
ORDER BY COMMISSION_PCT ASC , SALARY DESC;

-- b.
SELECT COUNTRY_NAME
FROM HR.COUNTRIES
ORDER BY COUNTRY_NAME;


